version: '2'

services:
  flask:
    image: pipecontrol-flask
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file: .env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /mnt:/mnt
      
  nginx:
    image: pipecontrol-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    env_file: .env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flask
